apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: demo
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-job
    spec:
      containers:
      - name: batch-container
        image: busybox:latest
        command: ["sh" , "-c" , "echo hello bhai! && sleep 10"]
      restartPolicy: Never
